### ISSUE TITLE
Usage Guidelines

### ISSUE THREAD

**Issue by joaquin-mendoza8** [csu-tide/csu-tide.github.io#11]

**Comment by joaquin-mendoza8** [comment]
Change NRP reference to TIDE

**Comment by kkrick-sdsu** [comment]
usage-guidelines.md
- Add `{:target="_blank"}` to all external links
- Line 10-11: remove
- Line 16: change "[see campus-specific information otherwise](/jupyterhub/gettingaccess#campus-specific-access)"
- Line 18: change "please check out the [Storage Services](/storage-services/) section"
- Line 21: change to include CSU Protected Level-1
- Line 27: change "Read and accept"
- Line 30: change to "all users who publish works with use of TIDE must include the following attribution to the NRP":
This work used resources available through the National Research Platform (NRP) at the
University of California, San Diego. NRP has been developed, and is supported in part, by funding
from National Science Foundation, from awards 1730158, 1540112, 1541349, 1826967,
2112167, 2100237, and 2120019, as well as additional funding from community partners

**Comment by joaquin-mendoza8** [comment]
Done
